india/urls.py
from django.urls import path
from india.views import*
app_name='india'
urlpatterns=[
    path('dhoni/',dhoni,name='dhoni'),
]

pakistan/urls.py
from django.urls import path
from pakistan.views import*
app_name='pakistan'
urlpatterns=[
    path('virat/',virat,name='virat'),
]

project13/urls.py
from django.contrib import admin
from django.urls import path,include
import india,pakistan,rashya
from pakistan.views import*
from india.views import *
from rashya.views import*

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sree/',sree,name='sree'),
    path('ram/',ram,name='ram'),
    path('seetha/',seetha,name='seetha'),
    path('india/',include('india.urls')),
    path('pakistan/',include('pakistan.urls')),
    path('rashya/',include('rashya.urls')),

]

rashya/urls.py
from django.urls import path
from rashya.views import*
app_name='rashya'
urlpatterns=[
    path('sachin/',sachin,name='sachin'),
]

india/models.py
from django.db import models

# Create your models here.

pakistan/models.py
from django.db import models

# Create your models here.

rashya/models.py
from django.db import models

# Create your models here.

india/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def dhoni(request):
    return render(request,'dhoni.html')
def ram(request):
    return HttpResponse('<h1>THIS IS RAM HTTPRESPONSE</h1>')   
    

pakistan/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def virat(request):
    return render(request,'virat.html')
def sree(request):
    return HttpResponse('<h1>HOW ARE U.....</h1>')

rashya/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def sachin(request):
    return render(request,'sachin.html')
def seetha(request):
    return HttpResponse('<h1>THIS IS SEETHA httpresponse</h1>')    

templates/dhoni.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>THIS IS DHONI PAGE</h1>
        <h1><a href="{% url 'pakistan:virat' %}">go to virat page</a></h1>
        <h1><a href="{% url 'rashya:sachin' %}">go to sachin page</a></h1>
        <h1><a href="{% url 'seetha' %}">go to seetha</a></h1>
        <h1><a href="{% url 'sree' %}">go to sree</a></h1>

    </center>
    
</body>
</html>

templates/sachin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>THIS IS SACHIN PAGE</h1>
        <h1><a href="{% url 'india:dhoni' %}">go to dhoni page</a></h1>
        <h1><a href="{%  url 'pakistan:virat' %}">go to virat page</a></h1>
        <h1><a href="{% url 'ram' %}">go to ram</a></h1>
        <h1><a href="{% url 'sree' %}">go to sree</a></h1>

    </center>
    
</body>
</html>

templates/virat.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>THIS IS VIRAT PAGE</h1>
        <h1><a href="{% url 'india:dhoni' %}">go to dhoni page</a></h1>
        <h1><a href="{%  url 'rashya:sachin' %}">go to sachin page</a></h1>
        <h1><a href="{% url 'seetha' %}">go to seetha</a></h1>
        <h1><a href="{% url 'ram' %}">go to ram</a></h1>


    </center>
    
</body>
</html>